import type {
  PlanningDashboardView,
  PlanningHierarchyView,
  SalesTargetPlan,
} from '@/store/server/features/salesTargeting/types';

export const MOCK_PLAN: SalesTargetPlan = {
  id: 'mock-plan-fy2026',
  name: 'Targets FY 2026/27',
  calendarId: 'mock-cal-2026',
  targetSettingMethod: 'BOTTOM_TO_TOP',
  status: 'active',
  tenantId: 'mock-tenant',
  currencyTargets: [
    {
      id: 'mock-curr-etb',
      planId: 'mock-plan-fy2026',
      currencyId: 'ETB',
      annualAmount: 2800000,
      tenantId: 'mock-tenant',
      currency: {
        id: 'ETB',
        name: 'ETB',
        description: 'Ethiopian Birr',
      },
      allocations: [],
    },
  ],
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-01-01T00:00:00Z',
};

export const MOCK_DASHBOARD: PlanningDashboardView = {
  planId: 'mock-plan-fy2026',
  planName: 'Targets FY 2026/27',
  calendarId: 'mock-cal-2026',
  targetSettingMethod: 'BOTTOM_TO_TOP',
  planStatus: 'ACTIVE',
  planningPhase: 'IN_PROGRESS',
  allowedPhaseTransitions: ['RECONCILIATION'],
  currencyId: 'ETB',
  horizon: 'annual',
  sessionId: null,
  metrics: {
    scopeLevel: 'company',
    scopeId: 'company-root',
    scopeName: 'Company',
    parentScopeId: null,
    currencyId: 'ETB',
    horizon: 'annual',
    sessionId: null,
    strategicTarget: 2800000,
    officialTarget: 2800000,
    proposedTarget: 2110000,
    originalProposal: 2110000,
    reviewedTarget: 2110000,
    currentForecast: 2800000,
    forecastAtProposal: 2800000,
    actualWon: 850000,
    gap: -690000,
    coverage: 75.35,
    requestId: null,
    requestStatus: 'OFFICIAL',
    eligibleActions: [],
  },
  completionSummary: {
    totalTeams: 4,
    teamsWithProposal: 3,
    teamsApproved: 2,
    teamsPending: 1,
    departmentsTotal: 4,
    departmentsSubmitted: 3,
    membersTotal: 11,
    membersWithProposal: 1,
    membersPending: 1,
    blockedEntities: 0,
    completionPercent: 75,
    bottleneckLabel: '1 awaiting review',
  },
};

export const MOCK_HIERARCHY: PlanningHierarchyView = {
  planId: 'mock-plan-fy2026',
  currencyId: 'ETB',
  horizon: 'annual',
  sessionId: null,
  root: {
    scopeLevel: 'company',
    scopeId: 'company-root',
    scopeName: 'Company',
    parentScopeId: null,
    currencyId: 'ETB',
    horizon: 'annual',
    sessionId: null,
    strategicTarget: 2800000,
    officialTarget: 2800000,
    proposedTarget: 2110000,
    originalProposal: 2110000,
    reviewedTarget: 2110000,
    currentForecast: 2800000,
    forecastAtProposal: 2800000,
    actualWon: 850000,
    gap: null,
    coverage: 75,
    requestId: null,
    requestStatus: 'OFFICIAL',
    eligibleActions: [],
    children: [
      {
        scopeLevel: 'department',
        scopeId: 'dept-sales',
        scopeName: 'Sales',
        parentScopeId: 'company-root',
        currencyId: 'ETB',
        horizon: 'annual',
        sessionId: null,
        strategicTarget: null,
        officialTarget: 1980000,
        proposedTarget: 1980000,
        originalProposal: 1980000,
        reviewedTarget: 1980000,
        currentForecast: 1980000,
        forecastAtProposal: 1980000,
        actualWon: 650000,
        gap: null,
        coverage: 75,
        requestId: 'req-dept-sales',
        requestStatus: 'PENDING_COMPANY',
        eligibleActions: [],
        children: [
          {
            scopeLevel: 'team',
            scopeId: 'team-sales-a',
            scopeName: 'Sales Team A',
            parentScopeId: 'dept-sales',
            currencyId: 'ETB',
            horizon: 'annual',
            sessionId: null,
            strategicTarget: null,
            officialTarget: 700000,
            proposedTarget: 850000,
            originalProposal: 850000,
            reviewedTarget: 700000,
            currentForecast: 850000,
            forecastAtProposal: 850000,
            actualWon: 300000,
            gap: null,
            coverage: 100,
            requestId: 'req-team-a',
            requestStatus: 'OFFICIAL',
            eligibleActions: [],
            children: [],
          },
          {
            scopeLevel: 'team',
            scopeId: 'team-sales-b',
            scopeName: 'Sales Team B',
            parentScopeId: 'dept-sales',
            currencyId: 'ETB',
            horizon: 'annual',
            sessionId: null,
            strategicTarget: null,
            officialTarget: null,
            proposedTarget: 700000,
            originalProposal: 700000,
            reviewedTarget: null,
            currentForecast: 700000,
            forecastAtProposal: 700000,
            actualWon: 200000,
            gap: null,
            coverage: 100,
            requestId: 'req-team-b',
            requestStatus: 'PENDING_DEPARTMENT',
            eligibleActions: [],
            children: [],
          },
          {
            scopeLevel: 'team',
            scopeId: 'team-sales-c',
            scopeName: 'Sales Team C',
            parentScopeId: 'dept-sales',
            currencyId: 'ETB',
            horizon: 'annual',
            sessionId: null,
            strategicTarget: null,
            officialTarget: null,
            proposedTarget: 430000,
            originalProposal: 430000,
            reviewedTarget: null,
            currentForecast: 430000,
            forecastAtProposal: 430000,
            actualWon: 150000,
            gap: null,
            coverage: 100,
            requestId: 'req-team-c',
            requestStatus: 'PENDING_TEAM',
            eligibleActions: [],
            children: [],
          },
          {
            scopeLevel: 'team',
            scopeId: 'team-sales-d',
            scopeName: 'Sales Team D',
            parentScopeId: 'dept-sales',
            currencyId: 'ETB',
            horizon: 'annual',
            sessionId: null,
            strategicTarget: null,
            officialTarget: null,
            proposedTarget: null,
            originalProposal: null,
            reviewedTarget: null,
            currentForecast: null,
            forecastAtProposal: null,
            actualWon: 0,
            gap: null,
            coverage: 0,
            requestId: null,
            requestStatus: null,
            eligibleActions: [],
            children: [],
          },
        ],
      },
      {
        scopeLevel: 'department',
        scopeId: 'dept-pre-sales',
        scopeName: 'Pre-Sales',
        parentScopeId: 'company-root',
        currencyId: 'ETB',
        horizon: 'annual',
        sessionId: null,
        strategicTarget: null,
        officialTarget: 80000,
        proposedTarget: 80000,
        originalProposal: 80000,
        reviewedTarget: 80000,
        currentForecast: 80000,
        forecastAtProposal: 80000,
        actualWon: 20000,
        gap: null,
        coverage: 25,
        requestId: 'req-dept-presales',
        requestStatus: 'PENDING_COMPANY',
        eligibleActions: [],
        children: [],
      },
      {
        scopeLevel: 'department',
        scopeId: 'dept-customer-success',
        scopeName: 'Customer Success',
        parentScopeId: 'company-root',
        currencyId: 'ETB',
        horizon: 'annual',
        sessionId: null,
        strategicTarget: null,
        officialTarget: null,
        proposedTarget: null,
        originalProposal: null,
        reviewedTarget: null,
        currentForecast: null,
        forecastAtProposal: null,
        actualWon: 0,
        gap: null,
        coverage: 0,
        requestId: null,
        requestStatus: null,
        eligibleActions: [],
        children: [],
      },
      {
        scopeLevel: 'department',
        scopeId: 'dept-a',
        scopeName: 'dept A',
        parentScopeId: 'company-root',
        currencyId: 'ETB',
        horizon: 'annual',
        sessionId: null,
        strategicTarget: null,
        officialTarget: 52870,
        proposedTarget: 52870,
        originalProposal: 52870,
        reviewedTarget: 52870,
        currentForecast: 52870,
        forecastAtProposal: 52870,
        actualWon: 10000,
        gap: null,
        coverage: 25,
        requestId: 'req-dept-a',
        requestStatus: 'PENDING_COMPANY',
        eligibleActions: [],
        children: [],
      },
    ],
  },
};
